_format_version: "3.0"
plugins:
  - config:
      echo_downstream: false
      generator: uuid
      header_name: x-uos-correlation-id
    enabled: true
    name: correlation-id
    ordering:
      before:
        access:
          - oas-validation
    protocols:
      - grpc
      - grpcs
      - http
      - https
  - config:
      content_type: application/json
      custom_fields_by_lua: []
      flush_timeout: 2
      headers:
        Authorization: Splunk 1fef7417-3fe0-46a1-801b-04164660a59b
      http_endpoint: https://prd-p-s3ws6.splunkcloud.com:8088/services/collector/raw
      keepalive: 60000
      method: POST
      queue:
        initial_retry_delay: 0.01
        max_batch_size: 10
        max_bytes: null
        max_coalescing_delay: 1
        max_entries: 10000
        max_retry_delay: 60
        max_retry_time: 60
      queue_size: null
      retry_count: null
      timeout: 10000
    enabled: true
    name: http-log
    protocols:
      - grpc
      - grpcs
      - http
      - https
  - config:
      allow:
        - 49.249.17.98
      deny: null
      message: The service is currently unavailable.
      status: null
    enabled: true
    name: ip-restriction
    protocols:
      - http
      - https
      - tcp
      - tls
      - grpc
      - grpcs
  - config:
      day: null
      error_code: 429
      error_message: API rate limit exceeded
      fault_tolerant: true
      header_name: null
      hide_client_headers: false
      hour: null
      limit_by: consumer
      minute: null
      month: null
      path: null
      policy: local
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_server_name: null
      redis_ssl: false
      redis_ssl_verify: false
      redis_timeout: 2000
      redis_username: null
      second: 100
      year: null
    enabled: true
    name: rate-limiting
    protocols:
      - grpc
      - grpcs
      - http
      - https
  - config:
      allowed_payload_size: 100
      require_content_length: false
      size_unit: kilobytes
    enabled: true
    name: request-size-limiting
    protocols:
      - grpc
      - grpcs
      - http
      - https
services:
  - host: integration.dev-api.shef.ac.uk
    id: c3004a9c-c46e-57e7-8baf-e23d728fc9bb
    name: student-api-v1
    path: /
    plugins:
      - config:
          anonymous: null
          hide_credentials: false
          key_in_body: false
          key_in_header: true
          key_in_query: true
          key_names:
            - apikey
          run_on_preflight: true
        enabled: true
        name: key-auth
        protocols:
          - grpc
          - grpcs
          - http
          - https
          - ws
          - wss
      - config:
          functions:
            - |-
              return function(status, body, headers)
                  local new_body = {}

                  if status == 400 then
                      new_body = {
                          code = 10000,
                          description = "Required fields are missing or invalid data specified in the request. Please refer the swagger specification for more details",
                          source = "Middleware",
                          message = body.message,
                          type = "Validation"
                      }
                  elseif status == 401 then
                      new_body = {
                          code = 10001,
                          description = "Unauthorised request",
                          source = "Middleware",
                          message = body.message,
                          type = "Validation"
                      }
                  elseif status == 403 then
                      new_body = {
                          code = 10002,
                          description = "Forbidden request",
                          source = "Middleware",
                          message = body.message,
                          type = "Validation"
                      }
                  elseif status == 500 then
                      new_body = {
                          code = 20000,
                          description = "Internal Server Error",
                          source = "Error",
                          message = body.message,
                          type = "Server error"
                      }
                elseif status == 503 then
                      new_body = {
                          code = 20000,
                          description = "Internal Server Error",
                          source = "Error",
                          message = body.message,
                          type = "System"
                      }
                  else
                      -- For any other status codes, return the original body
                      return status, body, headers
                  end

                  return status, new_body, headers
              end
        enabled: true
        name: exit-transformer
        protocols:
          - grpc
          - grpcs
          - http
          - https
      - config:
          anonymous: null
          audience: null
          audience_claim:
            - aud
          audience_required: null
          auth_methods:
            - bearer
          authenticated_groups_claim: null
          authorization_cookie_domain: null
          authorization_cookie_http_only: true
          authorization_cookie_name: authorization
          authorization_cookie_path: /
          authorization_cookie_same_site: Default
          authorization_cookie_secure: null
          authorization_endpoint: null
          authorization_query_args_client: null
          authorization_query_args_names: null
          authorization_query_args_values: null
          authorization_rolling_timeout: 600
          bearer_token_cookie_name: null
          bearer_token_param_type:
            - header
            - query
            - body
          by_username_ignore_case: false
          cache_introspection: true
          cache_token_exchange: true
          cache_tokens: true
          cache_tokens_salt: dC1MclTHUAJ8SGzPH90fEMAFN4xFZ9yj
          cache_ttl: 3600
          cache_ttl_max: null
          cache_ttl_min: null
          cache_ttl_neg: null
          cache_ttl_resurrect: null
          cache_user_info: true
          client_alg: null
          client_arg: client_id
          client_auth: null
          client_credentials_param_type:
            - header
            - query
            - body
          client_id: []
          client_jwk: null
          client_secret: []
          consumer_by:
            - username
            - custom_id
          consumer_claim: null
          consumer_optional: false
          credential_claim:
            - sub
          disable_session: null
          discovery_headers_names: null
          discovery_headers_values: null
          display_errors: false
          domains: null
          downstream_access_token_header: null
          downstream_access_token_jwk_header: null
          downstream_headers_claims: null
          downstream_headers_names: null
          downstream_id_token_header: null
          downstream_id_token_jwk_header: null
          downstream_introspection_header: null
          downstream_introspection_jwt_header: null
          downstream_refresh_token_header: null
          downstream_session_id_header: null
          downstream_user_info_header: null
          downstream_user_info_jwt_header: null
          enable_hs_signatures: false
          end_session_endpoint: null
          expose_error_code: true
          extra_jwks_uris: null
          forbidden_destroy_session: true
          forbidden_error_message: Forbidden
          forbidden_redirect_uri: null
          groups_claim:
            - groups
          groups_required: null
          hide_credentials: false
          http_proxy: null
          http_proxy_authorization: null
          http_version: 1.1
          https_proxy: null
          https_proxy_authorization: null
          id_token_param_name: null
          id_token_param_type:
            - header
            - query
            - body
          ignore_signature: []
          introspect_jwt_tokens: false
          introspection_accept: application/json
          introspection_check_active: true
          introspection_endpoint: null
          introspection_endpoint_auth_method: null
          introspection_headers_client: null
          introspection_headers_names: null
          introspection_headers_values: null
          introspection_hint: access_token
          introspection_post_args_client: null
          introspection_post_args_names: null
          introspection_post_args_values: null
          introspection_token_param_name: token
          issuer: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_pmhLhUYdx
          issuers_allowed: null
          jwt_session_claim: sid
          jwt_session_cookie: null
          keepalive: true
          leeway: 0
          login_action: upstream
          login_methods:
            - authorization_code
          login_redirect_mode: fragment
          login_redirect_uri: null
          login_tokens:
            - id_token
          logout_methods:
            - POST
            - DELETE
          logout_post_arg: null
          logout_query_arg: null
          logout_redirect_uri: null
          logout_revoke: false
          logout_revoke_access_token: true
          logout_revoke_refresh_token: true
          logout_uri_suffix: null
          max_age: null
          mtls_introspection_endpoint: null
          mtls_revocation_endpoint: null
          mtls_token_endpoint: null
          no_proxy: null
          password_param_type:
            - header
            - query
            - body
          preserve_query_args: false
          proof_of_possession_auth_methods_validation: true
          proof_of_possession_mtls: "off"
          pushed_authorization_request_endpoint: null
          pushed_authorization_request_endpoint_auth_method: null
          redirect_uri: null
          rediscovery_lifetime: 30
          refresh_token_param_name: null
          refresh_token_param_type:
            - header
            - query
            - body
          refresh_tokens: true
          require_proof_key_for_code_exchange: null
          require_pushed_authorization_requests: null
          resolve_distributed_claims: false
          response_mode: query
          response_type:
            - code
          reverify: false
          revocation_endpoint: null
          revocation_endpoint_auth_method: null
          revocation_token_param_name: token
          roles_claim:
            - roles
          roles_required: null
          run_on_preflight: true
          scopes:
            - openid
          scopes_claim:
            - scope
          scopes_required: null
          search_user_info: false
          session_absolute_timeout: 86400
          session_audience: default
          session_compressor: none
          session_cookie_domain: null
          session_cookie_http_only: true
          session_cookie_maxsize: 4000
          session_cookie_name: session
          session_cookie_path: /
          session_cookie_renew: 600
          session_cookie_same_site: Lax
          session_cookie_secure: null
          session_enforce_same_subject: false
          session_hash_storage_key: false
          session_hash_subject: false
          session_idling_timeout: 900
          session_memcached_host: 127.0.0.1
          session_memcached_port: 11211
          session_memcached_prefix: null
          session_memcached_socket: null
          session_redis_cluster_max_redirections: null
          session_redis_cluster_nodes: null
          session_redis_connect_timeout: null
          session_redis_host: 127.0.0.1
          session_redis_password: null
          session_redis_port: 6379
          session_redis_prefix: null
          session_redis_read_timeout: null
          session_redis_send_timeout: null
          session_redis_server_name: null
          session_redis_socket: null
          session_redis_ssl: false
          session_redis_ssl_verify: false
          session_redis_username: null
          session_remember: false
          session_remember_absolute_timeout: 2592000
          session_remember_cookie_name: remember
          session_remember_rolling_timeout: 604800
          session_request_headers: null
          session_response_headers: null
          session_rolling_timeout: 3600
          session_secret: null
          session_storage: cookie
          session_store_metadata: false
          session_strategy: default
          ssl_verify: false
          timeout: 10000
          tls_client_auth_cert_id: null
          tls_client_auth_ssl_verify: true
          token_cache_key_include_scope: false
          token_endpoint: null
          token_endpoint_auth_method: null
          token_exchange_endpoint: null
          token_headers_client: null
          token_headers_grants: null
          token_headers_names: null
          token_headers_prefix: null
          token_headers_replay: null
          token_headers_values: null
          token_post_args_client: null
          token_post_args_names: null
          token_post_args_values: null
          unauthorized_destroy_session: true
          unauthorized_error_message: Unauthorized
          unauthorized_redirect_uri: null
          unexpected_redirect_uri: null
          upstream_access_token_header: authorization:bearer
          upstream_access_token_jwk_header: null
          upstream_headers_claims: null
          upstream_headers_names: null
          upstream_id_token_header: null
          upstream_id_token_jwk_header: null
          upstream_introspection_header: null
          upstream_introspection_jwt_header: null
          upstream_refresh_token_header: null
          upstream_session_id_header: null
          upstream_user_info_header: null
          upstream_user_info_jwt_header: null
          userinfo_accept: application/json
          userinfo_endpoint: null
          userinfo_headers_client: null
          userinfo_headers_names: null
          userinfo_headers_values: null
          userinfo_query_args_client: null
          userinfo_query_args_names: null
          userinfo_query_args_values: null
          using_pseudo_issuer: false
          verify_claims: true
          verify_nonce: true
          verify_parameters: false
          verify_signature: true
        enabled: true
        name: openid-connect
        protocols:
          - grpc
          - grpcs
          - http
          - https
      - config:
          day: null
          error_code: 429
          error_message: API rate limit exceeded
          fault_tolerant: true
          header_name: null
          hide_client_headers: false
          hour: null
          limit_by: consumer
          minute: null
          month: null
          path: null
          policy: local
          redis_database: 0
          redis_host: null
          redis_password: null
          redis_port: 6379
          redis_server_name: null
          redis_ssl: false
          redis_ssl_verify: false
          redis_timeout: 2000
          redis_username: null
          second: 10
          year: null
        enabled: true
        name: rate-limiting
        protocols:
          - grpc
          - grpcs
          - http
          - https
      - config:
          add:
            body: []
            headers: []
            querystring: []
          append:
            body: []
            headers: []
            querystring: []
          http_method: null
          remove:
            body: []
            headers: []
            querystring: []
          rename:
            body: []
            headers: []
            querystring: []
          replace:
            body: []
            headers:
              - 'Authorization: aniket'
            querystring: []
            uri: null
        enabled: true
        name: request-transformer
        protocols:
          - grpc
          - grpcs
          - http
          - https
      - config:
          allowed_payload_size: 10
          require_content_length: false
          size_unit: kilobytes
        enabled: true
        name: request-size-limiting
        protocols:
          - grpc
          - grpcs
          - http
          - https
    port: 443
    protocol: https
    routes:
      - id: cb41ec15-5e1e-5652-9180-c62bcc5768f7
        methods:
          - GET
        name: student-api-v1_getstudents
        paths:
          - ~/v1/students$
        plugins:
          - config:
              allow:
                - UoS-group
              deny: null
              hide_groups_header: false
              include_consumer_groups: false
            enabled: true
            name: acl
            protocols:
              - grpc
              - grpcs
              - http
              - https
        regex_priority: 200
        strip_path: false
        tags: []
    tags: []
upstreams: []
