name: publish Spec to Kong
on: [push]
jobs:
  OAS_TO_Kong:
    runs-on: ubuntu-latest
    steps:
      - name: Checkou repository
        uses: actions/checkout@v3

      - name: download yq
        run: |
          sudo snap install yq
          yq --version
          
      - name: append the value in the kong config file
        run: |
          yq -i '.services[].plugins[] |= (select(.name == "request-transformer") | .config.replace.headers |= [{"Authorization": "Authorization: ${{ secrets.BASIC_AUTH }}"}])' kong-config.yaml
          cat kong-config.yaml
