name: publish Spec to Kong
on: [push, pull_request]
jobs:
  OAS_TO_Kong:
    runs-on: ubuntu-latest
    steps:
      - name: Checkou repository
        uses: actions/checkout@v3

      - name: download yq
        run: |
          sudo snap install yq
          yq --version
          
      - name: see files
        run: ls -al
    
      - name: Configuring Git
        run: |  
            cd api/Apiconfig/Kongconfig           
            git config --local user.email "action@github.com"
            git config --local user.name "Github Action"

      # - name: Commit and Push Changes if file not exist
      #   if: env.confirmation == 'false' 
      #   run: |
      #     cd api/Apiconfig/Kongconfig
      #     git add .
      #     git commit -m "Update Kong config and plugins file"
      #     git push origin ${{ github.event.inputs.select_branch }}  
      
      # - name: Check branch status and Overwriting exiting files  
      #   if: env.confirmation == 'true'
      #   run: |
      #     cd api/Apiconfig/Kongconfig
      #     BRANCH_STATUS=$(git status --porcelain)

      #     # Check if the message contains nothing
      #     if [[ -z "$BRANCH_STATUS" ]]; then
      #       echo "Branch is up to date. Skipping remaining steps."
      #       exit 0
      #     else
      #     echo "Branch needs further processing. Continue with remaining steps."
      #     git add .
      #     git commit -m "Update Kong config and plugins file"
      #     git push origin ${{ github.event.inputs.select_branch }}
      #     fi     
          
