---
name: konnect-global-configuration
on:
  push:
    branches:
      - main

  workflow_dispatch:     
jobs:
  Global_Plugin_Configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from another repository
        uses: actions/checkout@v2
        with:
          repository: 'Ani-maurya/integration-global-kong-configuration'
          ref: 'main'
          token: ${{ secrets.PAT }}

      - name: download jq
        run: |
          sudo apt install jq -y
          jq --version

      - name: download yq
        run: |
          sudo snap install yq
          yq --version

      - name: Install deck CLI
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.35.0/deck_1.35.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp 
          sudo cp /tmp/deck /usr/local/bin/

      - name: Add Global plugins
        run:  cat ./kong-global-config/kong.yaml | deck file add-plugins ./kong-global-config/dev-global-plugin.yaml -o kong.yaml    

      - name: Apply Global Configuration
        run: >
          deck gateway sync  --select-tag dev kong.yaml --konnect-token ${{ secrets.DECK_TOKEN }} --konnect-control-plane-name A-global-configuration
