---
name: konnect-global-configuration
on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch    
jobs:
  Global_Plugin_Configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from kong global config
        uses: actions/checkout@v2
        with:
          repository: 'Ani-maurya/integration-global-kong-configuration'
          ref: 'main'
          token: ${{ secrets.PAT }}
          path: plugin-config

      - name: Install deck CLI
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.35.0/deck_1.35.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp 
          sudo cp /tmp/deck /usr/local/bin/

      - name: Append Plugins to New file
        run: |
            ls -la plugin-config/kong-global-config
            if [ "${{ vars.KEY_AUTH }}" == "true" ] || [ "${{ vars.RATE_LIMITING }}" == "true" ] || [ "${{ vars.REQUEST_SIZE_LIMITING }}" == "true" ] || [ "${{ vars.HTTP_LOG }}" == "true" ] || [ "${{ vars.IP_RESTRICTION }}" =="true" ] || [ "${{ vars.CORRELATION_ID }}" == "true"]; then
              cd plugin-config/kong-global-config
              sed -i '1,2d' correlation.yaml ip-restriction.yaml key-auth.yaml rate-limiting.yaml request-size-limiting.yaml
              cat  http-log.yaml correlation.yaml ip-restriction.yaml key-auth.yaml rate-limiting.yaml request-size-limiting.yaml  > combined-plugins.yaml
              cat combined-plugins.yaml
            fi
      
      - name: Apply Global Configuration
        run: >
          deck gateway sync  --select-tag dev combined-plugins.yaml --konnect-token ${{ secrets.DECK_TOKEN }} --konnect-control-plane-name ${{ vars.GLOBAL_CONTROL_PLANE_NAME }}
