---
name: Publish Spec to Kong
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      student_api_repo_name:
        description: 'Student API repository name'
        required: true
      plugin_repo_name:
        description: 'Plugin reposistory name'
        required: true

jobs:
  OAS_TO_Kong:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from global config
        uses: actions/checkout@v2
        with:
          repository: 'Ani-maurya/${{ github.event.inputs.plugin_repo_name }}'
          ref: 'main'
          token: ${{ secrets.PAT }}
          path: global-config

      - name: Checkout Code from student api
        uses: actions/checkout@v2
        with:
          repository: 'Ani-maurya/${{ github.event.inputs.student_api_repo_name }}'
          ref: 'main'
          token: ${{ secrets.PAT }}
          path: api
      
      # - name: list files from kong global config
      #   run: ls -la kong-student-api 

      # - name: list files from kong student api
      #   run: ls -la integration-global-kong-configuration

      - name: download jq
        run: |
          sudo apt install jq -y
          jq --version

      - name: download yq
        run: |
          sudo snap install yq
          yq --version

      - name: Install deck CLI
        run: >
          cd api/student-api
          curl -sL
          https://github.com/kong/deck/releases/download/v1.34.0/deck_1.34.0_linux_amd64.tar.gz
          -o deck.tar.gz

          tar -xf deck.tar.gz -C /tmp 

          sudo cp /tmp/deck /usr/local/bin/

          deck file openapi2kong -s api/student-api/Student_v0.4.yml --select-tag=dev -o kong.yaml

      - name: Append Plugins to new-api.yaml
        run: |
          cd api/student-api
          if [ "${{ vars.RATE_LIMITING }}" == "true"  || [ "${{ vars.REQUEST_SIZE_LIMITING }}" == "true" ] || [ "${{ vars.ACL }}" == "true" ] || "${{ vars.OAS_VALIDATION }}" == "true" ] || [ "${{ vars.OPENID_CONNECT }}" ==
          "true" ] ]; then
             sed -i '1,2d' global-config/request-size-limiting.yaml  global-config/oas-validation.yaml global-config/open-id.yaml global-config/acl.yaml
             sed -i '1d' global-config/ratelimiting.yaml
             cat  global-config/ratelimiting.yaml global-config/request-size-limiting.yaml global-config/oas-validation.yaml global-config/open-id.yaml > combined-plugins.yaml
             cat combined-plugins.yaml
             export plugins=$(cat combined-plugins.yaml)
             export route_plugins=$(cat global-config/acl.yaml)
             echo $plugins
             cat kong.yaml | yq '.services.[] += env(plugins)' -o yaml | yq '.services[].routes.[].plugins +=env(route_plugins)' -o yaml > kong-student-api.yaml
             # cat new-api.yaml | yq '.services.[] += env(plugins)' -o yaml > modified-api.yaml
          fi

      - name: check if file exists
        id: check_file
        run: |
          if [ -f "api/student-api/kong-student-api.yaml" ]; then
            echo "File already exits."
            echo "Prompting user for confirmation..."
            echo "Please confirm whether you want to override the existing file."
            echo "::set-output name=confirmation::true"
          else
            echo "File does not exist."
            echo "::set-output name=confirmation::false"
          fi

      - name: Create Issue for Confirmation
        if: steps.check_file.outputs.confirmation == 'true'
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Confirm Overwrite of kong configuration yaml file
          content: |
            The file 'kong-configuration.yaml' already exists  in the directory.
            Do you want to override the existing file?
            Please comment with either "confirm" or "cancel".

      - name: Wait for User Confirmation
        if: steps.check_file.outpus.confirmation == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number
            const { data: comments } = await github.issue.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number
            })

            const userCommnet = comments.find(comment => commnet.user.login !== 'github-action[bot]')
            if (userComment) {
                const response = userCommnet.body.trim().toLowerCase()
                if(reponse === 'confirm') {
                  console.log('User confirmed overwrite.')
                  console.log('::set-output name=confirmation::confirm')
                } else if (response === 'cancel') {
                  console.log('User cancelled overwrite.')
                  console.log('::set-output name=confirmation::cancel')
                } else {
                  console.log('Invalid response. Plse comment with either "confirm" or "cancel".')
                  console.log('::set-output name=confirmation::invalid')
                }
            } else {
              console.log('No user response detected yet.')
              console.log('::set-output name=confirmation::no-response')
            }

      - name: Check confirmation & Proceed and configuring Git
        if : steps.check_file.outputs.confirmation == 'true' && steps.Wait for User Confirmation.outputs.confirmation == 'confirm'
        run: | 
            echo "Confirmation received, proceeding with overwrite..."
            
            git config --local user.email "action@github.com"
            git config --local user.name "Github Action"
            git remote set --url origin https://github.com/Ani-maurya/integration-kong-student-api.git # set the remote URL of the target repository
            git config --local credential.helper store # store credentials temporarily
            echo "machine github.com login ${{ secrets.PAT }}" > ~/.netrc # use the PAT for authentication
      
      - name: Handle Cancellation
        if: steps.check_file.outpus.confirmation == 'true' && steps.Wait for User Confirmation.outputs.confirmation == 'cancel'
        run: |
          echo "Overwrite cancelled by user, exiting workflow."
          exit 1

      - name: Commit and Push Changes
        if: steps.check_file.outputs.confirmation == 'true'
        run: |
          cd api/student-api
          git add .
          git commit -m "Update kong file"
          git push origin main  # specify the remote and branch to push to

      - name: Set headers and run deck sync
        run: |
          cd api/student-api
          cat kong-student-api.yaml
          
          # deck file openapi2kong -s test.yaml --select-tag=dev -o kong.yaml

          deck gateway sync  --select-tag dev kong-student-api.yaml --konnect-token ${{ secrets.DECK_TOKEN }} --konnect-control-plane-name ${{ vars.CONTROL_PLANE_NAME }}
          
  publish-customer-api-to-portal:
    name: Publish OAS to dev portal
    needs: OAS_TO_Kong
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from another repository
        uses: actions/checkout@v2
        with:
          repository: Ani-maurya/${{ github.event.inputs.student_api_repo_name }}
          ref: main
          token: ${{ secrets.PAT }}

      - name: Fech environment variables
        id: set_env_vars
        run: |
          echo "API_PRODUCT_NAME: ${{ vars.API_PRODUCT_NAME }}"
          echo "CONTROL_PLANE_NAME: ${{ vars.CONTROL_PLANE_NAME }}" 
          echo "GATEWAY_SERVICE_NAME: ${{ vars.GATEWAY_SERVICE_NAME }}"
          echo "API_PRODUCT_ALREADY_EXISTS=false" >> $GITHUB_ENV

      - name: Check API Product is already exist or not or Creating new API product
        run: |
          response=$(curl -s --request GET \
            --url "${{ vars.ADMIN_API_URL }}/api-products" \
            --header "Authorization: ${{ secrets.PIPELINE_TOKEN }}")

          if [[ $response == *"${{ vars.API_PRODUCT_NAME }}"* ]]; then
              echo "API product already exists, Please change the API product name"
              echo "API_PRODUCT_ALREADY_EXISTS=true" >> $GITHUB_ENV
              
          else
            echo "API product dosen't exist, creating..."
            curl --request POST \
              --url ${{ vars.ADMIN_API_URL }}/api-products \
              --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
              --header 'Content-Type: application/json' \
              --data '{
                "name": "${{ vars.API_PRODUCT_NAME }}",
                "description": "Creating through admin api",
                "labels": {}
              }'
          fi 

      - name: Get API product ID
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: >
          api_product_name="${{ vars.API_PRODUCT_NAME }}"

          api_product_id=$(curl --request GET \
            --url ${{ vars.ADMIN_API_URL }}/api-products \
            --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
            | jq -r --arg api_product_name "$api_product_name" '.data[] | select(.name == $api_product_name) | .id // empty')

          if [ "$api_product_id" = "empty" ]; then
            echo "Error: API Product ID not found."
            exit 1
          fi

          echo "API_PRODUCT_ID=$api_product_id" >> $GITHUB_ENV 

      - name: Get Dev Portal ID
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: |
          Dev_portal_id=$(curl --request GET \
            --url ${{ vars.ADMIN_API_URL }}/portals \
            --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
            | jq -r '.data[].id')
              echo "DEV_PORTAL_ID=$Dev_portal_id" >> $GITHUB_ENV

      - name: Publish product to the dev portal
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: |
          echo "API Product ID: $API_PRODUCT_ID"
          echo "Dev Portal ID: $DEV_PORTAL_ID"
          curl --request PATCH \
           --url ${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID \
           --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
           --header 'Content-Type: application/json' \
           --data "{
             \"portal_ids\":[\"$DEV_PORTAL_ID\"]
           }"

      - name: Create the product version
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: >
          echo "API Product ID: $API_PRODUCT_ID"

          api_product_version_id=$(curl --request POST \
            --url ${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions \
            --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
              "name": "v1",
              "publish_status": "published",
              "gateway_service": null
            }'| jq -r '.id')
              echo "API_Product_Version_ID=$api_product_version_id" >> $GITHUB_ENV
              echo "API Product Version ID: $API_Product_Version_ID"

      - name: Get Control Plane ID
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: >
          control_plane_name="${{ vars.CONTROL_PLANE_NAME }}"

          control_plane_id=$(curl --location '${{ vars.ADMIN_API_URL }}/control-planes' \

          --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \

          | jq -r --arg control_plane_name "$control_plane_name" '.data[] | select(.name == $control_plane_name) | .id')

          echo "Control_Plane_ID=$control_plane_id" >> $GITHUB_ENV

      - name: Get Service ID
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: >
          echo "Control Plane Id: $Control_Plane_ID"

          gateway_service_name="${{ vars.GATEWAY_SERVICE_NAME }}"

          service_id=$(curl --location "${{ vars.ADMIN_API_URL }}/control-planes/$Control_Plane_ID/core-entities/services" \
            --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
            | jq -r --arg gateway_service_name "$gateway_service_name" '.data[] | select(.name == $gateway_service_name) | .id')
          echo "Service_ID=$service_id" >> $GITHUB_ENV

      - name: Link service to the product version
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: >
          echo "API PRODUCT ID: $API_PRODUCT_ID"

          echo "Control Plane ID: $Control_Plane_ID"

          echo "Service ID: $Service_ID"

          echo "API Product Version ID: $API_Product_Version_ID"

          curl --location --request PATCH "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID" \
                --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
                --header 'Content-Type: application/json' \
                --data "{
                        \"name\": \"v1\",
                        \"publish_status\": \"published\",
                        \"deprecated\": false,
                        \"notify\": true,
                        \"gateway_service\": {
                        \"control_plane_id\": \"$Control_Plane_ID\",
                        \"id\": \"$Service_ID\"
                                }
                       }"

      - name: Upload spec on the version
        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
        run: |
          echo "API PRODUCT ID: $API_PRODUCT_ID"
          echo "API Product Version ID: $API_Product_Version_ID"
          encoded_spec=$(base64 -w 0 Student_v0.4.yml)
          echo $encoded_spec
          curl --location --request POST "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID/specifications" \
            --header 'Authorization: ${{ secrets.PIPELINE_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
                    "name": "Student.yaml",
                    "content": "'"$encoded_spec"'"
                  }'
